using UnityEngine;
using UnityEngine.InputSystem;

public class VehicleController:MonoBehaviour{
 public bool PlayerVehicle; public float MotorTorque=2200f,BrakeTorque=3500f,MaxSteerAngle=32f,ParkSteerSpeed=4f,SteerRate=55f;
 public WheelCollider FrontLeft,FrontRight,RearLeft,RearRight; public Transform FrontLeftVisual,FrontRightVisual,RearLeftVisual,RearRightVisual; public bool IsDriven{get;private set;}
 Rigidbody rb; Transform driver; ThirdPersonCamera cam; bool wasBraking;
 public void SetupWheels(){rb=GetComponent<Rigidbody>();CreateWheel("FL",new Vector3(-.82f,.25f,1.35f),out FrontLeft,out FrontLeftVisual);CreateWheel("FR",new Vector3(.82f,.25f,1.35f),out FrontRight,out FrontRightVisual);CreateWheel("RL",new Vector3(-.82f,.25f,-1.35f),out RearLeft,out RearLeftVisual);CreateWheel("RR",new Vector3(.82f,.25f,-1.35f),out RearRight,out RearRightVisual);}
 void CreateWheel(string n,Vector3 pos,out WheelCollider wc,out Transform visual){var g=new GameObject(n);g.transform.SetParent(transform,false);g.transform.localPosition=pos;wc=g.AddComponent<WheelCollider>();wc.radius=.34f;wc.suspensionDistance=.2f;var mesh=GameObject.CreatePrimitive(PrimitiveType.Cylinder);mesh.name=n+"Visual";mesh.transform.SetParent(g.transform,false);mesh.transform.localRotation=Quaternion.Euler(0,0,90);mesh.transform.localScale=new Vector3(.34f,.12f,.34f);Object.Destroy(mesh.GetComponent<Collider>());mesh.GetComponent<Renderer>().material=new Material(Shader.Find("Universal Render Pipeline/Lit")){color=new Color(.01f,.01f,.01f)};visual=mesh.transform;}
 void Update(){if(!PlayerVehicle||rb==null)return;Keyboard k=Keyboard.current;if(!IsDriven){if(k?.eKey.wasPressedThisFrame==true&&NearPlayer())Enter();return;}if(k?.fKey.wasPressedThisFrame==true||k?.eKey.wasPressedThisFrame==true)Exit();float throttle=(k?.wKey.isPressed==true?1:0)-(k?.sKey.isPressed==true?1:0);float steer=(k?.dKey.isPressed==true?1:0)-(k?.aKey.isPressed==true?1:0);float speed=rb.linearVelocity.magnitude*3.6f;float steerAngle=steer*MaxSteerAngle;FrontLeft.steerAngle=steerAngle;FrontRight.steerAngle=steerAngle;float torque=throttle*MotorTorque;FrontLeft.motorTorque=torque;FrontRight.motorTorque=torque;RearLeft.motorTorque=torque;RearRight.motorTorque=torque;float brake=throttle==0?BrakeTorque:0;if(wasBraking)brake=BrakeTorque;FrontLeft.brakeTorque=FrontRight.brakeTorque=RearLeft.brakeTorque=RearRight.brakeTorque=brake;wasBraking=throttle==0;if(Mathf.Abs(steer)>.01f&&speed<ParkSteerSpeed)transform.Rotate(0,steer*SteerRate*Time.deltaTime,0,Space.World);UpdateVisual(FrontLeft,FrontLeftVisual);UpdateVisual(FrontRight,FrontRightVisual);UpdateVisual(RearLeft,RearLeftVisual);UpdateVisual(RearRight,RearRightVisual);}
 bool NearPlayer(){var p=GameObject.FindGameObjectWithTag("Player");return p&&Vector3.Distance(p.transform.position,transform.position)<4.5f;}
 void Enter(){var p=GameObject.FindGameObjectWithTag("Player");if(!p)return;driver=p.transform;var cc=p.GetComponent<CharacterController>();if(cc)cc.enabled=false;p.SetActive(false);IsDriven=true;cam=Camera.main?Camera.main.GetComponent<ThirdPersonCamera>():null;if(cam)cam.SetTarget(transform);}
 void Exit(){if(!driver)return;Transform exit=transform;driver.gameObject.SetActive(true);driver.position=transform.position-transform.right*2.4f+Vector3.up*.1f;driver.rotation=transform.rotation;var cc=driver.GetComponent<CharacterController>();if(cc)cc.enabled=true;IsDriven=false;var p=driver;driver=null;cam=Camera.main?Camera.main.GetComponent<ThirdPersonCamera>():null;if(cam)cam.SetTarget(p);}
 void UpdateVisual(WheelCollider wc,Transform v){wc.GetWorldPose(out var p,out var q);v.position=p;v.rotation=q*Quaternion.Euler(0,0,90);}
}
