import * as THREE from 'three';
import { PointerLockControls } from 'three/addons/controls/PointerLockControls.js';
import './style.css';

const scene=new THREE.Scene();
const camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.05,700);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});
renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;document.querySelector('#game').appendChild(renderer.domElement);
const menu=document.querySelector('#menu'),pause=document.querySelector('#pause'),promptEl=document.querySelector('#prompt'),ammoEl=document.querySelector('#ammo'),healthFill=document.querySelector('#healthFill'),wantedEl=document.querySelector('#wanted'),cashEl=document.querySelector('#cash'),locationEl=document.querySelector('#location'),vehicleNameEl=document.querySelector('#vehicleName'),speedEl=document.querySelector('#speed'),vehicleHud=document.querySelector('#vehicleHud'),minimap=document.querySelector('#minimap'),mapCanvas=document.querySelector('#mapCanvas'),mapCtx=mapCanvas.getContext('2d');
const controls=new PointerLockControls(camera,document.body),clock=new THREE.Clock(),raycaster=new THREE.Raycaster(),keys={};
const world=new THREE.Group(),city=new THREE.Group(),interiors=new THREE.Group(),actors=new THREE.Group(),vehicles=new THREE.Group(),fx=new THREE.Group();scene.add(world,city,interiors,actors,vehicles,fx);
let started=false,pausedNow=false,health=100,ammo=12,reserve=120,fireCooldown=0,reloadTimer=0,wanted=0,wantedDecay=0,cash=2500,dayTime=13,inInterior=false,activeBuilding=null,player,currentVehicle=null,showMap=true,cameraYaw=Math.PI,cameraPitch=.12;
const colliders=[],buildings=[],cars=[];const tmp=new THREE.Vector3(),dir=new THREE.Vector3(),targetPos=new THREE.Vector3();
const mats={road:new THREE.MeshStandardMaterial({color:0x242932,roughness:.94}),sidewalk:new THREE.MeshStandardMaterial({color:0x888b89,roughness:1}),grass:new THREE.MeshStandardMaterial({color:0x496045,roughness:1}),concrete:new THREE.MeshStandardMaterial({color:0xb4b1a8,roughness:.9}),glass:new THREE.MeshStandardMaterial({color:0x41697a,roughness:.14,metalness:.25}),black:new THREE.MeshStandardMaterial({color:0x101316,roughness:.5,metalness:.25}),white:new THREE.MeshStandardMaterial({color:0xe2e5e7,roughness:.7}),lamp:new THREE.MeshStandardMaterial({color:0xffd98a,emissive:0xff8b22,emissiveIntensity:2}),red:new THREE.MeshStandardMaterial({color:0xa53b35,roughness:.75}),blue:new THREE.MeshStandardMaterial({color:0x2e5d91,roughness:.72}),green:new THREE.MeshStandardMaterial({color:0x466c4e,roughness:.9})};
const box=(w,h,d,m,x,y,z,p=city)=>{const q=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);q.position.set(x,y,z);q.castShadow=true;q.receiveShadow=true;p.add(q);return q};
const cyl=(r,h,m,x,y,z,p=city)=>{const q=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,10),m);q.position.set(x,y,z);q.castShadow=true;p.add(q);return q};
const d2=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);const addCollider=(x,z,w,d)=>colliders.push({x,z,w,d});
const collides=(x,z,r=.65)=>colliders.some(c=>Math.abs(x-c.x)<c.w/2+r&&Math.abs(z-c.z)<c.d/2+r);
function makeRoads(){box(240,.16,26,mats.road,0,0,0);box(240,.16,26,mats.road,0,0,55);box(26,.16,240,mats.road,0,0,27);box(26,.16,240,mats.road,55,0,27);[[0,-15.5,240,5],[0,15.5,240,5],[0,39.5,240,5],[0,70.5,240,5],[-15.5,27,5,240],[15.5,27,5,240],[39.5,27,5,240],[70.5,27,5,240]].forEach(([x,z,w,d])=>box(w,.18,d,mats.sidewalk,x,.12,z));for(let x=-110;x<=110;x+=14){box(7,.03,.14,mats.white,x,.1,-.8);box(7,.03,.14,mats.white,x,.1,55.8)}for(let z=-80;z<=130;z+=14){box(.14,.03,7,mats.white,-.8,.1,z);box(.14,.03,7,mats.white,55.8,.1,z)}}
function makeBuilding(x,z,w,d,h,color,name){const g=new THREE.Group();g.position.set(x,0,z);city.add(g);box(w,h,d,new THREE.MeshStandardMaterial({color,roughness:.84}),0,h/2,0,g);for(let y=3;y<h-1;y+=3.1)for(let px=-w/2+2.2;px<w/2-1;px+=4.4){box(2.2,1.25,.08,mats.glass,px,y,d/2+.04,g);box(2.2,1.25,.08,mats.glass,px,y,-d/2-.04,g)}const door=box(2.3,2.9,.16,mats.black,0,1.45,d/2+.1,g);door.userData.enterDoor=true;door.userData.building=name;box(Math.min(w-4,11),1,.16,mats.red,0,Math.min(h-1.1,8),d/2+.17,g);const interior=new THREE.Group();interior.position.set(x,0,z+.1);interior.visible=false;interiors.add(interior);box(w-1,.2,d-1,mats.concrete,0,0,0,interior);box(w-1,.2,d-1,mats.black,0,6,0,interior);box(.2,6,d-1,mats.concrete,-(w-1)/2,3,0,interior);box(.2,6,d-1,mats.concrete,(w-1)/2,3,0,interior);box(w-1,6,.2,mats.concrete,0,3,-(d-1)/2,interior);for(let i=0;i<4;i++)box(2,1.1,2,i%2?mats.blue:mats.red,-w/3+i*4,1,-d/4,interior);g.userData={name,interior,doorWorld:new THREE.Vector3(x,1.45,z+d/2+.35),size:{w,d,h}};buildings.push(g);addCollider(x,z,w,d)}
function makeCity(){makeRoads();box(240,.1,240,mats.grass,0,-.08,27);[[-46,-45,24,25,18,0x7d7268,'OCEAN VIEW HOTEL'],[47,-45,24,25,26,0x69737e,'PACIFIC TOWER'],[-47,42,25,25,13,0x82776d,'VESPUCCI MARKET'],[47,42,25,25,20,0x6c7075,'ARCADE PLAZA'],[92,10,28,22,16,0x796b60,'EASTSIDE LOFTS'],[-92,10,28,22,22,0x596a70,'WESTSIDE OFFICES']].forEach(v=>makeBuilding(...v));for(let x=-110;x<=110;x+=11)for(const z of[-12.5,12.5,42.5,72.5]){if(Math.abs(x)<20&&z<60)continue;cyl(.18,5,mats.black,x,2.5,z);cyl(.48,.08,mats.lamp,x,5.1,z)}for(let i=0;i<45;i++){const x=(Math.random()-.5)*220,z=(Math.random()-.5)*210+27;if(Math.abs(x%55)<19||Math.abs(z%55)<19)continue;cyl(.22,2.8,new THREE.MeshStandardMaterial({color:0x594438}),x,1.4,z);const c=new THREE.Mesh(new THREE.IcosahedronGeometry(1.55,1),mats.green);c.position.set(x,3.3,z);c.castShadow=true;city.add(c)}}
function makePlayer(){player=new THREE.Group();player.position.set(0,0,12);const body=new THREE.Mesh(new THREE.CapsuleGeometry(.42,.95,5,10),new THREE.MeshStandardMaterial({color:0x3e4652,roughness:.7}));body.position.y=1;body.castShadow=true;player.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.3,12,10),new THREE.MeshStandardMaterial({color:0xb9896c,roughness:.9}));head.position.y=1.82;player.add(head);const shirt=new THREE.Mesh(new THREE.BoxGeometry(.65,.38,.38),new THREE.MeshStandardMaterial({color:0x253044}));shirt.position.set(0,1.45,0);player.add(shirt);world.add(player)}
function makeCar(x,z,color,rotation=0,traffic=true){const g=new THREE.Group();g.position.set(x,.52,z);g.rotation.y=rotation;g.userData={speed:traffic?4+Math.random()*2:0,traffic,occupied:false,name:'SENTINEL'};box(4.1,.75,1.85,new THREE.MeshStandardMaterial({color,roughness:.58,metalness:.2}),0,.35,0,g);box(2,.62,1.56,mats.glass,-.2,.9,0,g);for(const wx of[-1.38,1.38])for(const wz of[-.9,.9])cyl(.34,.18,mats.black,wx,.12,wz,g).rotation.z=Math.PI/2;const lamp=new THREE.Mesh(new THREE.BoxGeometry(.13,.1,.65),new THREE.MeshBasicMaterial({color:0xffdf9b}));lamp.position.set(2.06,.48,0);g.add(lamp);vehicles.add(g);cars.push(g)}
function makeTraffic(){const colors=[0x9e3434,0x345f8a,0xd0c4a5,0x292d31,0x64845a,0x8c6333];for(let i=0;i<30;i++){const road=i%2===0,p=-105+Math.random()*210;makeCar(road?p:(i%4<2?7:48),road?(i%4<2?7:48):p,colors[i%colors.length],road?Math.PI/2:0,true)}}
function makeNPC(x,z,police=false){const g=new THREE.Group();g.position.set(x,1,z);const body=new THREE.Mesh(new THREE.CapsuleGeometry(.36,.9,4,8),new THREE.MeshStandardMaterial({color:police?0x294b73:0x8a4c41}));body.castShadow=true;body.userData.actor=g;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.25,10,8),new THREE.MeshStandardMaterial({color:0xb98a6d}));head.position.y=.82;head.userData.actor=g;g.add(head);g.userData={health:100,police,dir:Math.random()*Math.PI*2,speed:police?2.8:1.05,shotAt:0};actors.add(g)}
function makeNPCs(){for(let i=0;i<34;i++)makeNPC((Math.random()-.5)*205,(Math.random()-.5)*175+27)}
function setWanted(v){wanted=THREE.MathUtils.clamp(v,0,5);wantedEl.textContent='★'.repeat(wanted)+'☆'.repeat(5-wanted);wantedEl.style.color=wanted?'#f3d35a':'#657080'}function updateAmmo(){ammoEl.textContent=`${ammo} / ${reserve}`}function damagePlayer(n){if(currentVehicle)return;health=Math.max(0,health-n);healthFill.style.width=health+'%';document.body.classList.add('damage');setTimeout(()=>document.body.classList.remove('damage'),180);if(health<=0)respawn()}function respawn(){health=100;ammo=12;reserve=120;setWanted(0);reloadTimer=0;currentVehicle=null;player.visible=true;player.position.set(0,0,12);updateAmmo();healthFill.style.width='100%';locationEl.textContent='VESPUCCI DISTRICT'}function reload(){if(reloadTimer<=0&&ammo<12&&reserve>0)reloadTimer=1.05}
function fire(){if(!started||pausedNow||!controls.isLocked||currentVehicle||reloadTimer>0||fireCooldown>0)return;if(ammo<=0){reload();return}ammo--;fireCooldown=.14;updateAmmo();const origin=camera.position.clone();controls.getDirection(dir);raycaster.set(origin,dir);const hit=raycaster.intersectObjects(actors.children,true).find(h=>h.object.userData.actor);if(hit){const a=hit.object.userData.actor;a.userData.health-=50;a.userData.shotAt=performance.now();hitFX(hit.point);setWanted(wanted+(a.userData.police?2:1));cash+=a.userData.police?50:25;cashEl.textContent='$'+cash.toLocaleString();if(a.userData.health<=0)a.removeFromParent()}else tracer(origin,origin.clone().add(dir.multiplyScalar(40)))}
function tracer(a,b){const dd=b.clone().sub(a),m=new THREE.Mesh(new THREE.CylinderGeometry(.014,.014,6,5),new THREE.MeshBasicMaterial({color:0xffd27a}));m.position.copy(a.clone().add(dd.normalize().multiplyScalar(3)));m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dd.normalize());fx.add(m);setTimeout(()=>m.removeFromParent(),55)}function hitFX(p){const g=new THREE.Group(),m=new THREE.MeshBasicMaterial({color:0xffd27a});for(let i=0;i<4;i++){const q=new THREE.Mesh(new THREE.BoxGeometry(.07,.07,.65),m);q.rotation.y=i*Math.PI/2;g.add(q)}g.position.copy(p);fx.add(g);setTimeout(()=>g.removeFromParent(),90)}
function nearestCar(){let best=null,bd=3.5;for(const c of cars)if(!c.userData.occupied){const d=d2(player.position,c.position);if(d<bd){bd=d;best=c}}return best}function enterCar(c){currentVehicle=c;c.userData.occupied=true;player.visible=false;vehicleHud.classList.add('active');locationEl.textContent='CITY STREETS';setWanted(wanted+1)}function exitCar(){if(!currentVehicle)return;const c=currentVehicle,side=new THREE.Vector3(0,0,2.4).applyQuaternion(c.quaternion);player.position.copy(c.position).add(side);player.position.y=0;player.visible=true;c.userData.occupied=false;currentVehicle=null;vehicleHud.classList.remove('active')}function enterBuilding(b){inInterior=true;activeBuilding=b;b.visible=false;b.userData.interior.visible=true;player.visible=true;player.position.set(0,0,0);camera.position.set(b.position.x,2.7,b.position.z);locationEl.textContent=b.userData.name}function exitBuilding(){if(!activeBuilding)return;activeBuilding.visible=true;activeBuilding.userData.interior.visible=false;player.position.copy(activeBuilding.userData.doorWorld).setY(0);inInterior=false;activeBuilding=null;locationEl.textContent='VESPUCCI DISTRICT'}function interact(){if(currentVehicle){exitCar();return}if(inInterior){exitBuilding();return}const c=nearestCar();if(c){enterCar(c);return}let b=null,bd=4.3;for(const g of buildings){const d=d2(player.position,g.userData.doorWorld);if(d<bd){bd=d;b=g}}if(b)enterBuilding(b)}
function updateOnFoot(dt){if(!controls.isLocked||pausedNow||inInterior)return;const speed=(keys.ShiftLeft||keys.ShiftRight)?8:4.8;let x=0,z=0;if(keys.KeyW)z-=1;if(keys.KeyS)z+=1;if(keys.KeyA)x-=1;if(keys.KeyD)x+=1;if(x||z){const len=Math.hypot(x,z);x/=len;z/=len;const f=new THREE.Vector3(Math.sin(cameraYaw),0,Math.cos(cameraYaw));const r=new THREE.Vector3(f.z,0,-f.x);const v=f.multiplyScalar(-z).add(r.multiplyScalar(x)).multiplyScalar(speed*dt);const nx=player.position.x+v.x,nz=player.position.z+v.z;if(!collides(nx,nz))player.position.set(nx,0,nz);player.rotation.y=Math.atan2(v.x,v.z)}player.position.x=THREE.MathUtils.clamp(player.position.x,-116,116);player.position.z=THREE.MathUtils.clamp(player.position.z,-112,142)}
function updateVehicle(dt){if(!currentVehicle||!controls.isLocked||pausedNow)return;const c=currentVehicle;let throttle=0;if(keys.KeyW)throttle=1;if(keys.KeyS)throttle=-.7;const boost=keys.ShiftLeft||keys.ShiftRight?1.35:1;const turn=(keys.KeyA?-1:0)+(keys.KeyD?1:0);c.userData.speed=THREE.MathUtils.lerp(c.userData.speed,throttle*15*boost,.09);c.rotation.y-=turn*dt*(.95+Math.abs(c.userData.speed)/18);const f=new THREE.Vector3(Math.sin(c.rotation.y),0,Math.cos(c.rotation.y)),next=c.position.clone().add(f.multiplyScalar(c.userData.speed*dt));if(!collides(next.x,next.z,1.9)&&Math.abs(next.x)<118&&Math.abs(next.z)<116)c.position.copy(next);else c.userData.speed*=.3;speedEl.textContent=Math.round(Math.abs(c.userData.speed)*4.7)+' KM/H'}
function updateTraffic(dt){for(const c of cars){if(c===currentVehicle||!c.userData.traffic)continue;const f=new THREE.Vector3(Math.sin(c.rotation.y),0,Math.cos(c.rotation.y));c.position.add(f.multiplyScalar(c.userData.speed*dt));if(c.position.x>122||c.position.x<-122||c.position.z>146||c.position.z<-116){if(Math.abs(Math.sin(c.rotation.y))>.5)c.position.x=c.position.x>0?-120:120;else c.position.z=c.position.z>0?-114:144}}}
function updateActors(dt){for(const a of actors.children){const u=a.userData, p=currentVehicle?currentVehicle.position:player.position,dd=d2(a.position,p);if(u.police){tmp.subVectors(p,a.position).setY(0);if(tmp.length()>7)a.position.add(tmp.normalize().multiplyScalar(u.speed*dt));a.lookAt(p.x,a.position.y,p.z);if(wanted&&dd<22&&performance.now()-u.shotAt>1500){u.shotAt=performance.now();damagePlayer(5)}}else{u.dir+=(Math.random()-.5)*dt*.7;a.position.x+=Math.cos(u.dir)*u.speed*dt;a.position.z+=Math.sin(u.dir)*u.speed*dt;if(Math.abs(a.position.x)>112||Math.abs(a.position.z)>118)u.dir+=Math.PI}}if(wanted){const nearby=actors.children.some(a=>a.userData.police&&d2(a.position,currentVehicle?currentVehicle.position:player.position)<38);if(!nearby)wantedDecay+=dt;else wantedDecay=0;if(wantedDecay>12){setWanted(wanted-1);wantedDecay=0}const count=actors.children.filter(a=>a.userData.police).length;if(count<Math.ceil(wanted/2)){const p=currentVehicle?currentVehicle.position:player.position,ang=Math.random()*Math.PI*2;makeNPC(p.x+Math.cos(ang)*32,p.z+Math.sin(ang)*32,true)}}}
function updateCamera(dt){const focus=(currentVehicle||player).position.clone();focus.y=currentVehicle?.position.y+1.1:1.15;const distance=currentVehicle?8:6.5;const off=new THREE.Vector3(Math.sin(cameraYaw)*distance,2.5+cameraPitch*2,Math.cos(cameraYaw)*distance);targetPos.copy(focus).add(off);camera.position.lerp(targetPos,Math.min(1,dt*8));camera.lookAt(focus.x,focus.y,focus.z)}
function updatePrompt(){if(currentVehicle)promptEl.textContent='F  EXIT VEHICLE';else if(inInterior)promptEl.textContent='E  EXIT BUILDING';else{const c=nearestCar();if(c){promptEl.textContent='E  ENTER VEHICLE';return}let b=null,bd=4.3;for(const g of buildings){const d=d2(player.position,g.userData.doorWorld);if(d<bd){bd=d;b=g}}promptEl.textContent=b?'E  ENTER '+b.userData.name:''}}
function drawMap(){if(!showMap)return;mapCtx.clearRect(0,0,220,220);mapCtx.fillStyle='rgba(8,11,16,.84)';mapCtx.fillRect(0,0,220,220);const s=.82,to=(x,z)=>[110+x*s,110+z*s];mapCtx.strokeStyle='rgba(255,255,255,.16)';mapCtx.lineWidth=7;for(const [x,z,w,d] of[[0,0,240,26],[0,55,240,26],[0,27,26,240],[55,27,26,240]]){const p=to(x,z);mapCtx.strokeRect(p[0]-w*s/2,p[1]-d*s/2,w*s,d*s)}for(const b of buildings){const p=to(b.position.x,b.position.z);mapCtx.fillStyle='#68707c';mapCtx.fillRect(p[0]-9,p[1]-9,18,18)}for(const c of cars.slice(0,25)){const p=to(c.position.x,c.position.z);mapCtx.fillStyle=c===currentVehicle?'#f5c451':'#9aa2ad';mapCtx.fillRect(p[0]-2,p[1]-2,4,4)}const pp=currentVehicle?.position||player.position,p=to(pp.x,pp.z);mapCtx.fillStyle='#fff';mapCtx.beginPath();mapCtx.arc(p[0],p[1],5,0,Math.PI*2);mapCtx.fill()}
function updateWorld(dt){dayTime=(dayTime+dt*.025)%24;const night=dayTime<6||dayTime>19;scene.background.setHex(night?0x0d1525:0x8ba9c7);scene.fog.color.setHex(night?0x0d1525:0x8ba9c7);const sun=scene.getObjectByName('sun');if(sun)sun.intensity=night?.17:.78}
function setupLights(){scene.add(new THREE.HemisphereLight(0xd7e8ff,0x34402e,1.1));const sun=new THREE.DirectionalLight(0xffe5bd,.8);sun.name='sun';sun.position.set(-70,100,-40);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-130;sun.shadow.camera.right=130;sun.shadow.camera.top=130;sun.shadow.camera.bottom=-130;sun.shadow.camera.far=300;scene.add(sun);const l=new THREE.PointLight(0xff9a37,2.2,20);l.position.set(0,3,0);world.add(l)}
function start(){started=true;menu.classList.add('hidden');pause.classList.add('hidden');pausedNow=false;controls.lock()}controls.addEventListener('lock',()=>{pausedNow=false;pause.classList.add('hidden')});controls.addEventListener('unlock',()=>{if(started){pausedNow=true;pause.classList.remove('hidden')}});document.querySelector('#play').onclick=start;document.querySelector('#resume').onclick=start;
window.addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyE'&&!e.repeat)interact();if(e.code==='KeyF'&&!e.repeat)exitCar();if(e.code==='KeyR'&&!e.repeat)reload();if(e.code==='KeyM'&&!e.repeat){showMap=!showMap;minimap.classList.toggle('hidden',!showMap)}if(e.code==='Space')e.preventDefault()});window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('mousedown',e=>{if(e.button===0)fire()});window.addEventListener('mousemove',e=>{if(controls.isLocked){cameraYaw-=e.movementX*.0025;cameraPitch=THREE.MathUtils.clamp(cameraPitch+e.movementY*.0018,-.55,.55)}});window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
makeCity();makePlayer();makeTraffic();makeNPCs();setupLights();setWanted(0);updateAmmo();
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);fireCooldown=Math.max(0,fireCooldown-dt);if(reloadTimer>0){reloadTimer-=dt;if(reloadTimer<=0){const n=Math.min(12-ammo,reserve);ammo+=n;reserve-=n;updateAmmo()}}updateOnFoot(dt);updateVehicle(dt);updateTraffic(dt);updateActors(dt);updateCamera(dt);updatePrompt();updateWorld(dt);drawMap();renderer.render(scene,camera)}animate();